repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: pyre
        name: Pyre
        entry: poetry run pyre --strict --noninteractive check
        language: system
        pass_filenames: false
        types: [python]
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
